site_name: Akropolis wiki
repo_name: 'akropolisio/wiki'
repo_url: 'https://github.com/akropolisio/wiki'
extra_javascript:
  - js/init.js
site_description: 'Wiki for the Akropolis Project'
google_analytics: 
  - 'UA-141608436-1'
  - 'auto'
theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'purple'
  font:
      text: 'Overpass'
      code: 'Overpass Mono'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/akropolisio'
    - type: 'medium'
      link: 'https://medium.com/@akropolis'
    - type: 'twitter'
      link: 'https://twitter.com/akropolisio'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/akropolisio/'
    - type: 'telegram'
      link: 'https://t.me/akropolis_official'
  feature:
    tabs: false
markdown_extensions:
    - admonition
pages:
  - Home: 'index.md'
  - Team: 'team.md'
  - Partnerships: 'partners.md'
  - Design: 'design.md'
  - Blog Posts: 
    - 2019: 'blog/2019.md'
    - 2018: 'blog/2018.md'
  - Media Coverage: 'press.md'
  - Development: 
    - C2FC: 'c2fc/overview.md'
    - Akropolis Network: 'akro-protocol.md'
    - Contracts: 'contracts.md'
  - Lightpaper: 'lightpaper.md'
  - Whitepaper: 
    - May 2019: 'whitepaper.md'
    - March 2018: 'tech_whitepaper.md'
  - Tokenomics: 'tokenomics.md'
  - FAQ: 'FAQ.md'
  - Quest:
    - Quest 101:
      - Quest 101: '101.md'
      - Rules: 'tc.md'
      - How to register: 'reg.md'
      - Point System: 'pointsys.md'
    - Introductory articles:
      - Round 1: 'quest/round1.md'
      - Round 2: 'quest/round2.md'
      - Round 3: 'quest/round3.md'
      - Round 3: 'quest/round4.md'
    - Answers and recaps:
      - Round 1 Answers: 'quest/r1answers.md'   
      - Round 2 Answers: 'quest/r2answers.md'
      - Round 3 Answers: 'quest/r3answers.md'      
  - Library: 'library.md'
