site_name: Akropolis wiki
repo_name: 'akropolisio/wiki'
repo_url: 'https://github.com/akropolisio/wiki'
extra_javascript:
  - js/init.js
site_description: 'Wiki for the Akropolis Project'
theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'purple'
  font:
      text: 'Overpass'
      code: 'Overpass Mono'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/akropolisio'
    - type: 'medium'
      link: 'https://medium.com/@akropolis'
    - type: 'twitter'
      link: 'https://twitter.com/akropolisio'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/akropolisio/'
    - type: 'telegram'
      link: 'https://t.me/akropolis_official'
  feature:
    tabs: false
markdown_extensions:
    - admonition
pages:
  - Home: 'index.md'
  - Team: 'team.md'
  - Partnerships: 'partners.md'
  - Design: 'design.md'
  - Blog Posts: 
    - 2019: 'blog/2019.md'
    - 2018: 'blog/2018.md'
  - Media Coverage: 'press.md'
  - Development: 
    - C2FC: 'c2fc/overview.md'
    - Akropolis Network: 'akro-protocol.md'
    - Contracts: 'contracts.md'
  - Whitepaper: 'whitepaper.md'
  - Tokenomics: 'tokenomics.md'
  - FAQ: 'FAQ.md'
  - Library: 'library.md'
