site_name: Akropolis wiki
repo_name: 'akropolisio/wiki'
repo_url: 'https://github.com/akropolisio/wiki'
site_description: 'Wiki for the Akropolis Project'
theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'purple'
  font:
      text: 'Overpass'
      code: 'Overpass Mono'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/akropolisio'
    - type: 'medium'
      link: 'https://medium.com/@akropolis'
    - type: 'twitter'
      link: 'https://twitter.com/akropolisio'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/akropolisio/'
    - type: 'telegram'
      link: 'https://t.me/akropolis_official'
  feature:
    tabs: false
markdown_extensions:
    - admonition
pages:
  - Mission and Vision: 'index.md'
  - Team: 'team.md'
  - Partnerships: 'partnerships.md'
  - Design: 'design.md'
  - Blog Posts: 'blog/blog.md'
  - Press: 'press.md'
  - Development: 
    - C2FC: 'c2fc/overview.md'
    - Chamas.network: 'c2fc/overview.md'
